spring:
  application:
  name: demo

app:
  oauth2:
    google:
      client-id: ${GOOGLE_CLIENT_ID}
      client-secret: ${GOOGLE_CLIENT_SECRET}
      default-redirect-uri: ${GOOGLE_REDIRECT_URI}

resilience4j:
  ratelimiter:
    instances:
      google-auth:
        limit-for-period: 10
        limit-refresh-period: 60s
        timeout-duration: 0s